### ISSUE TITLE
Don't know how to modify application models using this component

### ISSUE THREAD

**Issue by RogerTaule** [nflaig/loopback4-migration#4]
Hi!
 I'm relatively new at using Loopback 4, and I want to add your component to my application because I find it can be very useful. 

I'm using PostgreSQL, and I would like to modify my model (for example, adding a new property) creating a migrating script, but after a few tries, I don't know how to do it... 

Could you help me? 

Thanks in advance!!

**Comment by nflaig** [comment]
Hi,

ok, so as far as I understood the script is getting executed properly but you are unsure how the `up()` method should look like.

Also you need to differentiate between migrating the schema vs data, the module is mostly designed to migrate data since schema migration can already be achieved by just updating the model and running `app.migrateSchema()`.

Lets assume we add the `fullName` property to our user model and when we create a new user it will automatically set to `firstName lastName`. Now the problem is that existing users on systems or even just on our local machine where our app is running do not have this `fullName` property, this is where the migration script comes into play which could look something like this..

> migrations/1.0.1.migration.ts

```ts
import { repository } from "@loopback/repository";
import { MigrationScript } from "loopback4-migration";
import { UserRepository } from "../repositories";

export class MigrateUserFullName implements MigrationScript {
    version = "1.0.1";
    scriptName = MigrateUserFullName .name;
    description = "add full name to users by combining first and last name";

    constructor(
        @repository(UserRepository)
        private userRepository: UserRepository
    ) {}

    async up(): Promise<void> {
        // retrieve all users without fullName property
        const users = await this.userRepository.find(
            { where: { fullName: { exists: false } } }
        );
        
        // set fullName property to each user
        const updateUsers = users.map(user => {
            this.userRepository.updateById(user.id, { fullName: `${user.firstName} ${user.lastName}` }))
       }

        await Promise.all(updateUsers);
    }
}
```

This script will be run if you database version is lower than `1.0.1` or if you did not run any migrations at all. You also need to make sure that the application version is equal or higher than `1.0.1` else the script would not be run.
The migration module will make sure that the migration script is only once.

I hope that helps, let me know if you need further help

**Comment by RogerTaule** [comment]
Thank you for your fast answer!
I now have understood what should up() and down() methods should look like and how they work with app.migrateSchema(). 
Unfortunately, I think the script is not getting executed properly and I don't know exactly how to fix it. I understand that the application version, which can be modified either in package.json or modifying the component configuration, but I'm not sure how or where I can check or modify my database version. 

Thank you again!!

**Comment by nflaig** [comment]
Usually, you don't need to configure the component at all, it will get the app version from package.json, use the existing datasource and discover all migrations scripts automatically if you have them in the `migrations` folder and used the naming convention `someScriptName.migration.ts`.

The module will create a migration entry in the database if a script is successfully ran which means it will not be executed anymore if you start the application, maybe you need to check if you already have an entry for that version in the db.
Also it will only execute scripts that are lower or equal you app version and compare them to the version of the database.

**Comment by nflaig** [comment]
@RogerTaule did you achieve what you were trying to do with the module? Let me know if you need further assistance
