### ISSUE TITLE
Can not run the README.md's example

### ISSUE THREAD

**Issue by aitorjs** [nflaig/loopback4-migration#6]
Hello! 
I want to use this package.I have started following the guide's example (https://github.com/nflaig/loopback4-migration#example). but nothing happens when I type _npm run migrate_ or _npm start_.

My package.json is on version 1.0.0. v14.5.0 node version. Updated loopback4. 
Those are the changes I made:

- Create the migration inside **src/migrations** with **1.0.1.migration.ts** name.

```ts
import {repository} from "@loopback/repository";
import {MigrationScript, migrationScript} from "loopback4-migration";
import {UserRepository} from "../repositories";

@migrationScript()
export class AddUserFullName implements MigrationScript {
  version = "1.0.1";
  scriptName = AddUserFullName.name;
  description = "add full name to users by combining first and last name";

  constructor(
    @repository(UserRepository)
    private userRepository: UserRepository
  ) { }

  async up(): Promise<void> {
    console.log("migrating")
    // retrieve all users without fullName property
    const users = await this.userRepository.find({where: {fullName: {exists: false}}});

    // add fullName property to each user
    const updateUsers = users.map(user =>
      this.userRepository.updateById(user.id, {
        fullName: `${user.firstName} ${user.lastName}`
      })
    );

    await Promise.all(updateUsers);
  }

  async down(): Promise<void> {
    console.log("migrating end")
    // remove fullName property from all users
    await this.userRepository.updateAll(<any>{
      $unset: {fullName: 0}
    });
  }
}
```

- I add those line in **src/application.ts**:

```ts
import {MongoDataSource} from "./datasources";
import {MigrationBindings} from "loopback4-migration";
import {AddUserFullName} from "./migrations";
...
export class BtcExplorerApplication extends BootMixin(
  ServiceMixin(RepositoryMixin(RestApplication)),
) {
...
   this.bind(MigrationBindings.CONFIG).to({
      appVersion: "1.0.0",
      dataSourceName: MongoDataSource.dataSourceName,
      modelName: "User",
      migrationScripts: [AddUserFullName]
    });
```

- When I type _npm run migrate_ or _npm run start_, not "migrating" not "migrating end" is printed
in the console and User collection has not a new "fullName" on any of their documents.

¿What I'm doing wrong? Thanks! :)

**Comment by nflaig** [comment]
Hi @aitorjs 👋 

based on the code snippets you provided it looks like you forgot to [bind the component in `application.ts`](https://github.com/nflaig/loopback4-migration#bind-the-component-in-applicationts). Also the migration scripts will run when the application starts not when you run `npm run migrate`. You can check in the database if a migration record was created if it already exists for `1.0.1.migration.ts` the script won't be executed.

One other thing is the config you are setting in `application.ts`:
- `appVersion: "1.0.0"` should not be required to set manually if you maintain the version in `package.json` as the app version will be automatically discovered
-  `dataSourceName: MongoDataSource.dataSourceName` if you only have one data source this can also be omitted
- `modelName: "User"` the module creates migration records in the database to keep track of applied migrations and this is the model name that should be used for the collection in mongodb, the default is `Migration`
- `migrationScripts: [AddUserFullName]` since you follow the naming convention the migration script will be automatically discovered

I hope that helps, let me know if you are facing any further issues

**Comment by aitorjs** [comment]
Hello @nflaig !

Thanks for the fast reply! :)

- I add this line: **this.component(MigrationComponent);** inside **src/application.ts**  before this line: **this.projectRoot = __dirname;**. I have deleted:
```ts
this.bind(MigrationBindings.CONFIG).to({
  appVersion: "1.0.0",
  dataSourceName: MongoDataSource.dataSourceName,
  modelName: "user",
  migrationScripts: [AddUserFullName]
});
```

- I type **npm start**.

- I see a console.log I put inside 1.0.1.migration.ts but no new "Migration" collection in mongodb.

¿Could be the versioning the problem? 1.0.0 on package.json. Migration version on 1.0.1. I would say no. ¿Any idea?

Thanks! :)

**Comment by nflaig** [comment]
@aitorjs your migration script should not have a higher version then the application itself, so if you app is on version `1.0.0` only scripts lower or equal that version will be executed.

> I see a console.log I put inside 1.0.1.migration.ts but no new "Migration" collection in mongodb.

does your app have multiple data sources?

**Comment by aitorjs** [comment]
I have change migration script version to **0.9.0** and the migration script name to **0.9.0.migration.ts** and I see the "migrating" console.log inside **up()**. :)

Two more little questions, please:
1. ¿When **down()** is called? 
2. I have 5 documents inside **User** collection. No one has _fullName_ in it. ¿Why **await this.userRepository.find({where: {fullName: {exists: false}}})** gets an empty array?

Thanks for all! :D

**Comment by nflaig** [comment]
> I have change migration script version to 0.9.0 

Ideally you want to use the version of the app when the scripts needs to run, lets say you add new feature which requires to updat the data in the database. You would then increase your app version to 1.1.0 and the script would also have version 1.1.0

> ¿When down() is called?

Whenever your db version is higher then your app version which happens if you run migration for 1.1.0 for example and then you downgrade your app back to 1.0.0. The down method should always revert the changes done by the up method. In some cases downgrading might not be possible, it really depends on the changes you are doing in the up method. Most of the time it should not be required to implement the down method.

> I have 5 documents inside User collection. No one has fullName in it. ¿Why await this.userRepository.find({where: {fullName: {exists: false}}}) gets an empty array?

Based on the code it should give you the 5 users without a fullName property. Maybe in your case the property does exist but is null? Hard to tell what the issue, I would need further information for that

**Comment by aitorjs** [comment]
>> Ideally you want to use the version of the app when the scripts needs to run, lets say you add new feature which requires to 
>> updat the data in the database. You would then increase your app version to 1.1.0 and the script would also have version 1.1.0

This is what I do :)

>> Whenever your db version is higher then your app version which happens if you run migration for 1.1.0 for example and then >> you downgrade your app back to 1.0.0. The down method should always revert the changes done by the up method. In some >> cases downgrading might not be possible, it really depends on the changes you are doing in the up method. Most of the time it >> should not be required to implement the down method.
> 

OK.

>> Based on the code it should give you the 5 users without a fullName property. Maybe in your case the property does exist but >> is null? Hard to tell what the issue, I would need further information for that

With null, the same result. Dont worry! :)

I would like to read the code and understand how the component was made.

Thanks for all
